version: 2.1

jobs:
  test:
    docker:
      - image: python:3.13.0
    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  
      - run:
          name: Run data analysis script
          command: python analysis.py  
      - run:
          name: Run unit tests
          command:  python3 -m pytest Tests  

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
